[project]
name = "mock-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "faker>=37.1.0",
    "flask>=3.1.1",
    "flask-jwt-extended>=4.7.1",
    "pandas>=2.2.3",
    "pymysql>=1.1.1",
]
